Language: 'en' #'en' -> ISO-639-1 code of English language / 'ru' -> ISO-639-1 code of Russian language.
Batch Size: 5 #An argument for files batch size to be processed between sleeps. Must be positive integer.
Sleep Time: 10 #An argument for sleep (in seconds) after batch processing. Must be positive integer.
