#Convert sentence string to corresponding ID
def strings_to_id(argument, language_id):
    switcher_0 = {
        "ruby": 0,
        "hi": 1,
        "hello": 1,
        "what is your name": 2,
        "what does your name mean": 3,
        "introduce yourself": 4,
        "who are you": 4,
        "what is your nationality": 5,
        "where are you from": 6,
        "what is your motherland": 6,
        "how old are you": 7,
        "what is your gender": 8,
        "are you a boy or a girl": 8,
        "are you a boy": 8,
        "are you a girl": 8,
        "do you have friends": 9,
        "am i your friend": 9,
        "are you my friend": 9,
        "how are you": 10,
        "what can you do": 11,
        "can you count": 12,
        "can you play games": 13,
        "what games can you play": 13,
        "how many games can you play": 13,
        "let's play a game": 14,
        "i want to play a game": 14,
        "let's play capitals": 15,
        "i want to play capitals": 15,
        "let's play twenty one": 16,
        "i want to play twenty one": 16,
        "are you a human": 17,
        "can you sing": 17,
        "can you cook": 17,
        "can you take a photo": 17,
        "can you take a selfie": 17,
        "can you eat": 17,
        "can you drink": 17,
        "can you get hungry": 17,
        "do you know my name": 17,
        "are you okay": 18,
        "are you a robot": 18,
        "can you dance": 18,
        "can you sleep": 18,
        "do you speak english": 18,
        "do you speak russian": 18,
        "dance": 19,
        "start to dance": 19,
        "come here": 20,
        "go forward": 21,
        "go back": 22,
        "go left": 23,
        "go right": 24,
        "lull me to sleep": 25,
        "play a lullaby": 25,
        "sleep": 26,
        "you can sleep": 26,
        "i want to sleep": 26,
        "shut down": 26,
        "power off": 26,
        "bye": 26,
        "goodbye": 26,
        "how many languages do you know": 27,
        "teach me the commands in russian": 28,
        "switch the language": 29,
        "change the language": 29,
        "speak in english": 30,
        "switch to english": 30,
        "speak in russian": 31,
        "switch to russian": 31,
    }
    #get() method of dictionary data type returns value of passed argument if it is present in dictionary.
    #Otherwise second argument will be assigned as default value of passed argument

    switcher_1 = {
        "руби": 0,
        "привет": 1,
        "здравствуй": 1,
        "как тебя зовут": 2,
        "что означает твое имя": 3,
        "представься": 4,
        "кто ты": 4,
        "какая у тебя нация": 5,
        "откуда ты": 6,
        "какая твоя родина": 6,
        "сколько тебе лет": 7,
        "какой твой пол": 8,
        "ты мальчик или девочка": 8,
        "ты мальчик": 8,
        "ты девушка": 8,
        "у тебя есть друзья": 9,
        "я твой друг": 9,
        "ты мой друг": 9,
        "как ты": 10,
        "что ты умеешь делать": 11,
        "ты можешь считать": 12,
        "ты можешь играть в игры": 13,
        "в какие игры ты можешь играть": 13,
        "во сколько игр ты можешь сыграть": 13,
        "давай сыграем в игру": 14,
        "я хочу поиграть в игру": 14,
        "давай сыграем в столицы": 15,
        "я хочу поиграть в столицы": 15,
        "давай сыграем в двадцать один": 16,
        "я хочу поиграть в двадцать один": 16,
        "ты человек": 17,
        "ты умеешь петь": 17,
        "ты умеешь готовить": 17,
        "ты умеешь сделать фото": 17,
        "ты умеешь сделать селфи": 17,
        "ты умеешь есть": 17,
        "ты умеешь пить": 17,
        "ты умеешь проголодаться": 17,
        "ты знаешь мое имя": 17,
        "ты в порядке": 18,
        "ты робот": 18,
        "ты умеешь танцевать": 18,
        "ты можешь спать": 18,
        "ты говоришь по английски": 18,
        "ты говоришь по русски": 18,
        "танцуй": 19,
        "начни танцевать": 19,
        "иди сюда": 20,
        "иди вперед": 21,
        "иди назад": 22,
        "иди налево": 23,
        "иди направо": 24,
        "убаюкивай меня": 25,
        "сыграй колыбельную": 25,
        "спи": 26,
        "ты можешь поспать": 26,
        "я хочу поспать": 26,
        "выключайся": 26,
        "выключи питание": 26,
        "пока": 26,
        "до свидания": 26,
        "сколько языков ты знаешь": 27,
        "научи меня команды на английском": 28,
        "переключи язык": 29,
        "смени язык": 29,
        "говори по русски": 30,
        "переключись на русский": 30,
        "говори по английски": 31,
        "переключись на английский": 31,
    }
    #get() method of dictionary data type returns value of passed argument if it is present in dictionary.
    #Otherwise second argument will be assigned as default value of passed argument

    if language_id == "0":
        return switcher_0.get(argument, -1)
    if language_id == "1":
        return switcher_1.get(argument, -1)
    return -1
