Project: Ruby
Languages:
  En: 0
  Ru: 1
Language: 0
Courses:
  Data Folder: Courses/Data
  TTS Folder: TTS/Courses
  Save Data: 1
  Checkpoint English: 0
  Checkpoint Russian: 3
  Saved Data Folder: Courses/Collection
Games:
  Capitals:
    Questions Number: 10
    Data Folder: Games/Capitals/Data
    TTS Folder: TTS/Capitals
  Twenty-one:
    TTS Folder: TTS/Twenty-one
STT:
  Model Folder: STT/Model
QA:
  Data Folder: QA/Data
Conversation:
  TTS Folder: TTS/Conversation
Startup:
  TTS Folder: TTS/Startup
Music:
  Dance Music Folder: Music/Dance
  Lullaby Music Folder: Music/Lullaby
