Project: Aralez
Languages:
  En: 0
  Ru: 1
Language: '0'
Games:
  Capitals:
    Questions Number: 10
    Data Folder: Games/Capitals/Data
    TTS Folder: TTS/Capitals
  Twenty-one:
    TTS Folder: TTS/Twenty-one
STT:
  Model Folder: STT/Model
QA:
  Model Folder: QA/Model
Conversation TTS:
  Clips Folder: TTS/Conversation
Startup TTS:
  Clips Folder: TTS/Startup
Actions:
  Dance:
    Music Folder: Dance/Music
